In [30]:
import pandas as pd
from utils_score import get_all_scores

In [31]:
climate_df = pd.read_csv("indices_France_REF-mensuelles.txt",sep=";")
pheno_df = pd.read_csv('plantes_sol.csv', sep=",")

In [32]:
climate_df.rename(columns= {"P�riode":"Période",'NORTNAV':'Tmin', 'NORTXAV':'Tmax', 'NORTAV':'Tmoy'},inplace=True)

In [33]:
climate_df

,Point,Latitude,Longitude,Contexte,Période,Mois,Tmoy,Tmin,Tmax,NORTXQ90,NORTXQ10,NORTNQ10,NORTNQ90,NORPAV,NORRR,NORPFL90,NORPINT,Unnamed: 17
0,282,41.4087,9.1577,REF,REF,1,8.38,4.73,12.02,14.91,8.22,-0.51,9.66,2.39,73.99,71.17,7.40,NaN
1,282,41.4087,9.1577,REF,REF,2,8.67,4.72,12.62,15.23,9.14,0.21,8.97,1.74,49.08,59.56,6.55,NaN
2,282,41.4087,9.1577,REF,REF,3,10.72,6.63,14.80,18.25,10.90,1.51,10.79,1.97,61.00,67.93,7.50,NaN
3,282,41.4087,9.1577,REF,REF,4,12.91,9.07,16.75,20.02,13.06,4.41,12.41,2.33,69.96,71.29,7.67,NaN
4,282,41.4087,9.1577,REF,REF,5,16.73,12.71,20.75,24.99,16.14,8.95,15.92,1.66,51.40,70.51,6.70,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103219,18945,51.0496,2.5071,REF,REF,8,17.92,15.41,20.43,24.11,17.10,13.15,17.40,1.82,56.56,64.60,6.34,NaN
103220,18945,51.0496,2.5071,REF,REF,9,16.05,13.15,18.94,21.98,15.83,10.24,15.47,2.09,62.74,63.69,6.57,NaN
103221,18945,51.0496,2.5071,REF,REF,10,12.36,9.99,14.73,17.72,11.25,6.45,12.88,2.48,77.02,67.14,6.21,NaN
103222,18945,51.0496,2.5071,REF,REF,11,8.07,6.19,9.94,13.45,5.44,1.49,10.11,2.37,71.24,60.41,5.76,NaN
103223,18945,51.0496,2.5071,REF,REF,12,5.46,3.86,7.05,10.60,2.70,-0.75,7.74,2.24,69.58,58.10,5.41,NaN

In [34]:
to_keep = ['species', 'temp_opt_min', 'Temp_Opt_Max', 'Temp_Abs_Min', 'Temp_Abs_Max', 'Rain_Opt_Min',
           'Rain_Opt_Max', 'Rain_Abs_Min', 'Rain_Abs_Max']
pheno_df[to_keep]

,species,temp_opt_min,Temp_Opt_Max,Temp_Abs_Min,Temp_Abs_Max,Rain_Opt_Min,Rain_Opt_Max,Rain_Abs_Min,Rain_Abs_Max
0,Colza,15,25,5,41,500,1000,400,2800
1,Soja,20,33,10,38,600,1500,450,1800
2,Orge,15,20,2,40,500,1000,200,2000
3,Manioc,20,29,10,35,1000,1500,500,5000
4,Basilic,18,27,7,36,1000,1600,600,4300
5,Pomme de terre,15,25,7,30,500,800,250,2000
6,Cacao,21,32,10,38,1200,3000,900,7600
7,Mais,18,33,10,47,600,1200,400,1800
8,Lavande,17,26,10,30,600,1000,400,1200
9,Riz,25,35,16,38,1500,2000,1000,4000
10,Blé compact,10,16,4,20,600,900,300,1600
11,Blé dur,17,25,6,30,500,700,400,800
12,Sorgho,22,35,8,40,400,600,300,700

In [35]:
species = pheno_df['species'].values
horizon = 'REF'
scenario = "REF"

In [36]:
species

array(['Colza', 'Soja', 'Orge', 'Manioc', 'Basilic', 'Pomme de terre',
       'Cacao', 'Mais', 'Lavande', 'Riz', 'Blé compact', 'Blé dur ',
       'Sorgho'], dtype=object)

In [38]:
for spe in species:
    
    get_all_scores(climate_df, pheno_df, spe, horizon, scenario).to_csv('score_ref'+spe+".csv")